"""
Revision ID: c796f841719d
Revises: 55296ad22e23
Create Date: 2026-01-01 01:05:30.525309+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c796f841719d"
down_revision: Union[str, None] = "55296ad22e23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guild_config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("error_message_customizations", sa.JSON(), nullable=True)
        )
        batch_op.add_column(sa.Column("error_embed_color", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "error_embed_title",
                sqlmodel.sql.sqltypes.AutoString(length=256),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guild_config", schema=None) as batch_op:
        batch_op.drop_column("error_embed_title")
        batch_op.drop_column("error_embed_color")
        batch_op.drop_column("error_message_customizations")

    # ### end Alembic commands ###
